### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by YannickBlais**

### CODE REVIEW

**Comment by YannickBlais** [comment]
@benjamintanweihao can you approve this?

**Review by jnd77 — APPROVED** [review]

**Comment by YannickBlais** [comment]
@ahamez : can you approve this PR?

**Comment by YannickBlais** [comment]
@MichaelBitard, @fcabestre, @dawagner : can you approve this PR?

**Comment by YannickBlais** [comment]
@MichaelBitard, @fcabestre, @dawagner : can you approve/merge this PR?

**Pull request merged**
